FROM node:24-alpine

# set working directory
WORKDIR /app

# install dependencies
COPY package*.json ./

RUN npm install

# copy source code
COPY . .

# build the app
RUN npm run build

# expose port 8080 for Cloud Run
EXPOSE 8080

CMD ["npm", "run", "preview"]