FROM node:24-alpine

# set working directory
WORKDIR /app

# install dependencies
COPY package*.json ./

RUN npm install

# copy source code
COPY . .

# build the app
RUN cp -r .next/static .next/standalone/.next/ && \
    cp -r public .next/standalone/ || true

EXPOSE 3000

CMD ["node", ".next/standalone/server.js"]