FROM node:24-alpine

# Install Redis
RUN apk update && apk add --no-cache redis

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Build your app
RUN npm run build

COPY swagger.yaml ./dist/

EXPOSE 5500 6379

CMD ["sh", "-c", "redis-server --daemonize yes && npm run start"]